contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #validation channel"
    url: https://nfcore.slack.com/channels/validation
    about: Discussion about the nf-core/validation pipeline
