name: nf-core AWS full size tests
# This workflow is triggered on published releases.
# It can be additionally triggered manually with GitHub actions workflow dispatch.
# It runs the -profile 'test_full' on AWS batch

on:
  release:
    types: [published]
  workflow_dispatch:


env:
  TOWER_BEARER_TOKEN: ${{ secrets.TOWER_BEARER_TOKEN }}
  TOWER_COMPUTE_ENV: ${{ secrets.TOWER_COMPUTE_ENV }}
  TOWER_WORKSPACE_ID: ${{ secrets.TOWER_WORKSPACE_ID }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}


jobs:
  run-awstest:
    name: Run AWS full tests
    if: github.repository == 'nf-core/testpipeline'
    runs-on: ubuntu-latest
    steps:
      - name: Launch workflow via tower
        # TODO nf-core: You can customise AWS full pipeline tests as required
        # Add full size test data (but still relatively small datasets for few samples)
        # on the `test_full.config` test runs with only one set of parameters
        run: |
          curl -X POST "https://api.tower.nf/workflow/launch?workspaceId=${{ secrets.TOWER_WORKSPACE_ID }}" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.TOWER_BEARER_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "launch": { 
              "id" : "string",
              "computeEnvId" : "${{ secrets.TOWER_WORKSPACE_ID }}",
              "pipeline" : "nf-core/testpipeline",
              "workDir" : "s3://${{ secrets.AWS_S3_BUCKET }}/work/testpipeline/results-${{ github.sha }}",
              "paramsText" : "{\"outdir\":\"s3://${{ secrets.AWS_S3_BUCKET }}/testpipeline/results-${{ github.sha }}\"}",
              "revision" : "${{ github.sha }}",
              "configProfiles" : ["test_full"],
              "resume" : false,
              "dateCreated" : "1970-01-01T00:00:00.000Z"
              }
            }' \
          --fail