name: nf-core download
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nf-core

      - name: Download the pipeline
        run: nf-core download rnaseq -r dev -c singularity --singularity-cache-copy -x tar.bz2 --force
